[project]
name = "robottraderslab-impulse"
version = "0.1.2"
description = "Impulse trading strategy plugin for the RobotTradersLab engine"
readme = "README.md"
requires-python = ">=3.13,<3.14"
license = "Apache-2.0"
dependencies = [
  "robottraderslab>=0.1.0",
  "pandas>=3.0.0",
]

[project.urls]
Homepage = "https://robottraders.io/lab/impulse"
Documentation = "https://robottraders.io/lab/docs/impulse.html"
Repository = "https://github.com/RobotTraders/RobotTradersLab-Impulse"

[project.entry-points."robot_traders_lab.strategies"]
impulse ="robottraderslab_impulse:ImpulseStrategy"

[project.entry-points."robot_traders_lab.indicators"]
impulse = "robottraderslab_impulse.chart_indicators:get_lightweight_chart_indicators"

[project.entry-points."robot_traders_lab.examples"]
impulse = "robottraderslab_impulse"

[build-system]
requires = ["uv_build>=0.10.4,<0.11.0"]
build-backend = "uv_build"


[tool.uv.build-backend]
module-name = "robottraderslab_impulse"

[dependency-groups]
dev = [
  "bandit[toml]==1.9.4",
  "mypy==1.20.0",
  "pandas-stubs==3.0.0.260204",
  "pytest==9.0.3",
  "pytest-asyncio==1.3.0",
  "pytest-cov==7.1.0",
  "ruff==0.15.10",
]

[tool.coverage.run]
omit = ["*/tests/*", "*/test_*.py"]

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
filterwarnings = [
  "ignore:enable_cleanup_closed ignored because.*:DeprecationWarning:aiohttp.connector",
]

[tool.mypy]
packages = ["robottraderslab_impulse"]
follow_imports = "normal"
python_version = "3.13"
color_output = true
show_error_codes = true
check_untyped_defs = true
disallow_untyped_defs = true
no_implicit_optional = true
warn_return_any = true
warn_unreachable = true
warn_unused_ignores = true
ignore_missing_imports = true
namespace_packages = true
incremental = true
cache_dir = ".mypy_cache"
exclude = '^(build/|dist/|\.venv/|.*tests/)'

[tool.bandit]
skips = ["B101"]

[tool.ruff]
target-version = "py313"

[tool.ruff.lint]
extend-select = ["I", "PT"]

[tool.ruff.lint.isort]
known-first-party = ["robottraderslab"]
