name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  ci:
    name: Continuous Integration
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Run the Plugin Checks
        uses: ./.github/actions/ci
        with:
          python-version: ${{ matrix.python-version }}
